spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=contact_management_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Server Port
server.port=8080

# Logging
logging.level.com.fatima=DEBUG
logging.level.org.springframework.security=DEBUG
